### PR TITLE
Batch Files and Linux Shell Scripts for Faster Setup

### PR DESCRIPTION
**Pull request by dandeto**
Instead of the user needing to type out their directory and different commands to install modules, compile animations, build the game, and launch a server via command prompt, the user now only needs to run batch files. This allows less technical people to setup the game easier, and saves time spent typing directories and commands.

### CODE REVIEW

**Comment by nolram88** [comment]
you wouldnt happen to have a linux box to do this as well would you?

**Comment by dandeto** [comment]
I do not, but I did some intense googling and manually converted my code. I cannot verify that they work properly. Hopefully they do. I apologize for any mistakes in advance.

**Comment by nolram88** [comment]
thanks a bunch ill give these a shot and get right back to you.

**Comment by dandeto** [comment]
Alight, so I found a bash shell emulator <a href="https://www.tutorialspoint.com/execute_bash_online.php"> here</a>. I can verify that animations.sh, and server.sh work properly.

**Comment by dandeto** [comment]
All files work like a charm. Feel free to pull.

**Pull request merged**
